### ISSUE TITLE
"How to test the app"

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/armadietto_ynh#1]
Followup of the question you answered on the chat  (because i'm not sure you're connected on it anymore, so answering there ;))

>Comment dois-je procéder pour qu'elle soit de nouveau testée ? How do I go about getting it tested again?

Nowadays, the usual way is to trigger the CI / automatic test suite.

For this, you need to transfer ownership of the repo to Yunohost-Apps (though of course we provide you with maintainership rights on the repo), then you can create a pull request on this app repo (even a dummy one) and type "!testme" in a comment to trigger a test on our dev CI : https://ci-apps-dev.yunohost.org/ci/

**Comment by bencharp** [comment]
@alexAubin : Thank you for taking the time to answer me here.
I've cleaned up my commits and will transfer the ownership of the repo to Yunohost-Apps.
Do I need to apply to join the Apps group in the XMPP room or will a request here be sufficient? 

I have a number of questions regarding the management of updates, version numbering, user account creation and integration with the sso and I don't know if it's possible to get feedback on the integration work already done...
